---
- name: Create Subscription for openshift-gitops-operator
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_location | default(omit) }}"
    username: "{{ openshift_user | default(omit) }}"
    password: "{{ openshift_password | default(omit) }}"
    wait: yes
    apply: yes
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: openshift-gitops-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for CRD
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_location | default(omit) }}"
    username: "{{ openshift_user | default(omit) }}"
    password: "{{ openshift_password | default(omit) }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: appprojects.argoproj.io
  register: crds
  until: ( crds.resources | length ) > 0
  retries: 100
  delay: 5

- name: Wait for namespace
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_location | default(omit) }}"
    username: "{{ openshift_user | default(omit) }}"
    password: "{{ openshift_password | default(omit) }}"
    api_version: v1
    kind: Namespace
    name: openshift-gitops
  register: ns
  until: ( ns.resources | length ) > 0
  retries: 100
  delay: 5

- name: Grant ArgoCD cluster-admin permissions
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_location | default(omit) }}"
    username: "{{ openshift_user | default(omit) }}"
    password: "{{ openshift_password | default(omit) }}"
    apply: yes
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: argocd-clusteradmin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: openshift-gitops-argocd-application-controller
          namespace: openshift-gitops
    
- name: Create Subscription for openshift-pipelines-operator-rh
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_location | default(omit) }}"
    username: "{{ openshift_user | default(omit) }}"
    password: "{{ openshift_password | default(omit) }}"
    wait: yes
    apply: yes
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-pipelines-operator-rh
        namespace: openshift-operators
      spec:
        channel: stable
        name: openshift-pipelines-operator-rh
        source: redhat-operators
        sourceNamespace: openshift-marketplace
