apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: sphinx-pipeline
  name: sphinx-pipeline-y2viy8
  namespace: sphinx
spec:
  params:
  - name: git-url
    value: https://root:plschange@gitlab.apps.ocp.int.tomwishaupt.nl/ansible-rubegoldberg/website.git
  - name: git-revision
    value: master
  pipelineRef:
    name: sphinx-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: data
    persistentVolumeClaim:
      claimName: pipeline-data
